minidlna.music:
 image: debian
 volumes:
   - /home/storage/music:/var/lib/minidlna/music
 entrypoint: /bin/true

minidlna:
 build: .
 volumes_from:
  - minidlna.music:rw
 ports:
  - 8200:8200
  - 1900:1900/udp
 tty: true
 stdin_open: true
 net: "host"

